service: pictionary-websocket-api 

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"
frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x

# you can overwrite defaults here
  stage: dev
  region: us-west-2

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:Query"
      Resource: arn:aws:dynamodb:us-west-2:762295491414:table/pictionary
    # - Effect: "Allow"
    #   Action:
    #     - "s3:PutObject"
    #   Resource:
    #     Fn::Join:
    #       - ""
    #       - - "arn:aws:s3:::"
    #         - "Ref" : "ServerlessDeploymentBucket"
    #         - "/*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  connectionHandler:
    handler: bin/connection
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
  defaultHandler:
    handler: bin/connection
    events:
      - websocket:
          route: $default
  drawHandler:
    handler: bin/connection
    events:
      - websocket:
          route: draw
          routeResponseSelectionExpression: $default
  chatHandler:
    handler: bin/chat
    events:
      - websocket:
          route: chat
          routeResponseSelectionExpression: $default

# resources:
#   DynamoPermission:
#     Type: AWS::DynamoDB::Table
#     Properties:
#       AttributeDefinitions:
#         - AttributeName: PK
#           AttributeType: S
#       BillingMode: PROVISIONED
#       GlobalSecondaryIndex:
#         IndexName: SK
#         KeySchema:
#           - AttributeName: SK
#             KeyType: HASH
#         Projection
#       KeySchema:
#         - AttributeName: PK
#           KeyType: HASH
#       ProvisionedThroughput:
#         ReadCapacityUnits: 5
#         WriteCapacityUnits: 5
#       TableName: pictionary
#       Tags: 
#         - Key: project
#           Value: pictionary
      # TimeToLiveSpecification: 
      #   AttributeName: ttl
      #   Enabled: false
#   Outputs:
#       NewOutput:
#         Description: "Description for the output"
#         Value: "Some output value"
